homeassistant:
  enabled: true
advanced:
  network_key:
    - 128
    - 13
    - 38
    - 1
    - 76
    - 101
    - 76
    - 164
    - 141
    - 123
    - 89
    - 221
    - 32
    - 128
    - 63
    - 102
  pan_id: 58006
  ext_pan_id:
    - 250
    - 249
    - 32
    - 167
    - 162
    - 229
    - 198
    - 134
  log_level: debug
mqtt:
  base_topic: zigbee2mqtt_lan
  server: mqtt://core-mosquitto:1883
  user: addons
  password: eich9ia5ahvae7rahmee1AewavushohChohc4theet6Ienaiphei1Oim8iedooxu
serial:
  port: tcp://192.168.1.41:6638
  adapter: zstack
  baudrate: 115200
frontend:
  enabled: true
  port: 8099
device_options: {}
version: 4
devices:
  '0xa4c138cd256aef56':
    friendly_name: protherm
  '0x00158d00048681f7':
    friendly_name: bathhouse_climate
  '0xa4c138357ecf3e4c':
    friendly_name: bathhouse_room_light
  '0xa49e69fffe014ee0':
    friendly_name: bathhouse_ir_heater
  '0xa4c13877995a1c32':
    friendly_name: bathhouse_porch_light
  '0xa4c138f1fa6eae89':
    friendly_name: bathhouse_heater
  '0xa4c138d847ff5892':
    friendly_name: bathhouse_bath_light_group1
  '0xa4c138d3859eb05c':
    friendly_name: bathhouse_bath_light_group2
  '0xa4c138f5ad2c4a13':
    friendly_name: bathhouse_steam_stove_controller
  '0xa4c138bb122b0448':
    friendly_name: bathhouse_heat_pump
  '0xa4c1386a9f805cb5':
    friendly_name: shoe_dryer
  '0xa4c1381d6d20d4a8':
    friendly_name: bathhouse_outdoor_light
  '0xa4c138e3d37737ce':
    friendly_name: bathhouse_boiler
  '0xe0798dfffec10ca5':
    friendly_name: bathhouse_steam_scene_switch
  '0xa4c138f66453ad9f':
    friendly_name: bathhouse_steam_bench_controller
  '0xa4c138bf469f6d1f':
    friendly_name: bathhouse_climate_secondary
availability:
  passive:
    timeout: 240
  enabled: true
  active:
    timeout: 10
